apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: amazon/aws-efs-csi-driver
    newName: docker-registry.internal.stuart.com/systems/amazon/aws-efs-csi-driver
    newTag: v1.2.0
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    newTag: v2.0.3-eks-1-18-1
  - name: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    newTag: v2.1.0-eks-1-18-1
  - name: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    newTag: v2.0.1-eks-1-18-1
